### ISSUE TITLE
sesinetd is still broken

### ISSUE THREAD

**Issue by yliceee** [pedohorse/houdini-nix#1]
Hi, since it seems like you're still updating this, your README example for starting the license server doesn't work. It fails with
```
id: ‘users’: no such user
```
which I think is the same issue breaking nixpkgs's version. Have you been able to get the license server running? Thanks!

**Comment by permahorse** [comment]
Hi! 
yes, i'm running it fine, sesinetd has bugs, so you have to work around it:

sesinetd by itself (as provided by vendor) apparently  expects groupname to belong to a user with the same name.
On most systems username and groupname for the main user are the same, so it's not a problem, but in NixOS default user group (as of now) is `users`, therefore it fails to start and manage license files.

but you can provide it with a proper user, and pass the same username for `--group` flag - this way it will warn about missing group, but will actually run fine, smth like `sesinetd --user username --group username -D`

just a note: sesinetd wrapper in this flake allows you to provide a custom directory for licenses, as stock sesinted seem to be hardcoded to use `/usr/lib/sesi`, so you run it like
`nix run .#sesinetd-19_5_773 -- ./path/to/licensesdir --user username --group username -D`

**Comment by yliceee** [comment]
Thanks, I missed that the group and user were the same in the docs. However even after creating a user that satisfies, I'm getting
```
chgrp: changing group of '/usr/lib/sesi': Invalid argument
chgrp: cannot access '/usr/lib/sesi/licenses': No such file or directory
chgrp: cannot access '/usr/lib/sesi/licenses.disabled': No such file or directory
chgrp: cannot access '/usr/lib/sesi/sesinetd_peak_usage.bin': No such file or directory
chgrp: changing group of '/tmp/houdini_temp/sesinetd.log': Invalid argument
chgrp: changing group of '/usr/lib/sesi': Invalid argument
chgrp: cannot access '/usr/lib/sesi/licenses': No such file or directory
chgrp: cannot access '/usr/lib/sesi/licenses.disabled': No such file or directory
chgrp: cannot access '/usr/lib/sesi/sesinetd_peak_usage.bin': No such file or directory
chgrp: changing group of '/tmp/houdini_temp/sesinetd.log': Invalid argument
```
The exact command I'm running is:
`nix run github:pedohorse/houdini-nix#sesinetd-19_5_716 -- ./my-lic -D`
(I'm omitting `--user` and `--group` since I just went ahead and created a user with the default name it expects, www-data).

**Comment by permahorse** [comment]
does it keep running after that?
for me it also gives out warnings since i provide a non-existent group, but it doesn't crash and keeps running and working fine.

my guess is that it assumes it's run as a su and tries to chgrp/chown the dir you provide, but it does not have the rights to.
(it does NOT actually need any super user rights to do any of it's licensing work)

i suggest trying in first to pass it your main user as both `--user` and `--group` - even though there is no such group - it will print warnings, but run fine.

i cannot currently test it with a pre-created default user for it, but that is an issue to fix indeed.

**Comment by yliceee** [comment]
Hey, thanks for your help and sorry for the delay. Indeed it is working properly when passing my username for both the --user and --group option. I'll close this.
